### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by alexott** [rollulus/kafka-streams-playground#1]
Thank you for providing examples of Kafka Stream + Scala. I'm trying to use them with current snapshot of Kafka Connector for Twitter, but get following exception:

```
Exception in thread "StreamThread-1" org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 1
Caused by: org.apache.kafka.common.errors.SerializationException: Could not find class TwitterStatus specified in writer's schema whilst finding reader's schema for a SpecificRecord.
```

I see the corresponding schema in Schema Registry, and it almost the same as in Avro file (except namespaces):

```
{"subject":"tweets-value","version":1,"id":1,"schema":"{\"type\":\"record\",\"name\":\"TwitterStatus\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"createdAt\",\"type\":\"string\"},{\"name\":\"favoriteCount\",\"type\":\"int\"},{\"name\":\"text\",\"type\":\"string\"},{\"name\":\"user\",\"type\":{\"type\":\"record\",\"name\":\"TwitterUser\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"screenName\",\"type\":\"string\"}],\"connect.name\":\"TwitterUser\"}}],\"connect.name\":\"TwitterStatus\"}"}
```

Maybe you know how this issue could be resolved?

**Comment by rollulus** [comment]
Thanks for reporting, I'll have a look.

**Comment by rollulus** [comment]
It was indeed due to the namespaces. The `TwitterStatus` in our [Twitter connector](https://github.com/Eneco/kafka-connect-twitter) was not namespaced, and this one was. The Avro to Java generator does not allow empty namespaces, hence I updated both our Twitter connector and these examples.

So, can you pull the newest Twitter connector and this repo, rebuild and retry? For me at least it works.

Thanks :+1:

**Comment by alexott** [comment]
Thank you! It works now - I suspected that the problem is in the namespaces, but still learning how to work with Avro, etc., and didn't think about updating the connector as well.  Maybe it makes sense to add this .avsc file into connector itself, so for other it would be easier to consume the data?

**Comment by rollulus** [comment]
I considered to add the .avsc to the connector, however, since the connect framework is serialization format agnostic, I decided not to do so. See, it is perfectly fine to instruct the connector to use JSON or a more exotic format; Avro is just one of the many options.
